// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n = Integer.parseInt(args[0]);
		int a = 0;
		int b = 0;
		for (int i = 0; i<n; i++) {
			double x = Math.random();
			if (x <= 0.5) {
				a++;
			} else {
				b++;
			}
		}
		if ((b == 0) || (a == 0)) {
			System.out.println(" > 0.5: " + b + " times");
			System.out.println(" <= 0.5: " + a + " times");
		} else {
			double ratio = a / (double)(b);
			System.out.println(" > 0.5: " + b + " times");
			System.out.println(" <= 0.5: " + a + " times");
			System.out.println("Ratio: " + ratio);
		}
	}
}
